name = "portfolio-feature-flags"
main = "packages/feature-flags/src/index.ts"
compatibility_date = "2024-11-28"

[[kv_namespaces]]
binding = "FEATURE_FLAGS"
id = "39adbb9db8fb437db45d5bd0bc285f4f"
preview_id = "2321e67477194ac696eb2c708e248d1e"

[vars]
ALLOWED_ORIGINS = "https://tylerearls.com,http://localhost:5173,http://localhost:3000,http://localhost:4173"
